### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by nataliaasaa** [nataliaasaa/Qualidade-de-dados-biodiversidade#2]
Para cada coluna identique a quantidade de linhas com dados faltantes (em alguns casos, o dado faltante é uma string vazia, em outros casos é uma string contendo algum valor do tipo: "sem informação"). Faça um método que retorna a média de dados faltantes por coluna

**Comment by mrcrdg** [comment]
Ok, vou criar uma nova branch "feature/missingData" para incluir essa feature ao projeto.

**Comment by mrcrdg** [comment]
Versão inicial do exercício está em c844af46701ba8fef75b41793a2278e6c70f75d4

**Comment by mrcrdg** [comment]
Código refatorado no commit: 9a9f8f5c13a56771d957b642ad5ac0205d5b790a
Novo cálculo para a média dos dados falantes por coluna.

**Comment by PedroNunes92** [comment]
Finalizado
