### ISSUE TITLE
executando a aplicação

### ISSUE THREAD

**Issue by silviostanzani** [nataliaasaa/Qualidade-de-dados-biodiversidade#20]
crie um script python com um caso simples de utilização da lib e todas as funcionalidades

**Comment by nataliaasaa** [comment]
Closed in #0321555b57e0bb029ba1fb3a870a138ed04508c4

**Comment by nataliaasaa** [comment]
Closed in: 0321555b57e0bb029ba1fb3a870a138ed04508c4

**Comment by nataliaasaa** [comment]
Closed in: 11860747846409fb5ca37950f90673d9b53fe160
(uncommmented)
